name: Deploiement Terraform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installation de Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Configuration des credentials AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      - name: Import des ressources existantes
        working-directory: ./infra
        run: |
          terraform import -var="public_key_pem=${{ secrets.PUBLIC_KEY_PEM }}" \
            module.s3.aws_s3_bucket.files kanza-file-api-files-dev || true

          terraform import -var="public_key_pem=${{ secrets.PUBLIC_KEY_PEM }}" \
            module.api_gateway.aws_cloudwatch_log_group.apigw \
            /aws/api-gateway/kanza-file-api || true

          terraform import -var="public_key_pem=${{ secrets.PUBLIC_KEY_PEM }}" \
            module.iam.aws_iam_policy.lambda_s3 \
            arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/kanza-file-api-lambda-s3-policy || true

          terraform import -var="public_key_pem=${{ secrets.PUBLIC_KEY_PEM }}" \
            module.iam.aws_iam_policy.lambda_dynamodb \
            arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/kanza-file-api-lambda-dynamo-policy || true

          terraform import -var="public_key_pem=${{ secrets.PUBLIC_KEY_PEM }}" \
            module.lambda.aws_lambda_function.presign \
            kanza-file-api-presign || true

      - name: Terraform Plan
        run: terraform plan -var="public_key_pem=${{ secrets.PUBLIC_KEY_PEM }}"
        working-directory: ./infra

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var="public_key_pem=${{ secrets.PUBLIC_KEY_PEM }}"
        working-directory: ./infra
